# Generated by Django 5.0.3 on 2024-03-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_director_alter_actor_options_alter_movie_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fess_in_world',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default='film', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_site.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='none', max_length=130, unique=True),
        ),
    ]
